/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: ['class', '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        bg: {
          base: 'var(--color-bg-base)',
          elevated: 'var(--color-bg-elevated)',
          sunken: 'var(--color-bg-sunken)',
          overlay: 'var(--color-bg-overlay)',
          glass: 'var(--color-bg-glass)',
          'glass-border': 'var(--color-bg-glass-border)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          tertiary: 'var(--color-text-tertiary)',
          disabled: 'var(--color-text-disabled)',
          inverse: 'var(--color-text-inverse)',
          'on-brand': 'var(--color-text-on-brand)',
        },
        border: {
          DEFAULT: 'var(--color-border)',
          subtle: 'var(--color-border-subtle)',
          strong: 'var(--color-border-strong)',
          brand: 'var(--color-border-brand)',
        },
        brand: {
          DEFAULT: 'var(--color-brand)',
          hover: 'var(--color-brand-hover)',
          light: 'var(--color-brand-light)',
          muted: 'var(--color-brand-muted)',
          zest: {
            50: 'hsl(33, 100%, 96%)',
            100: 'hsl(33, 100%, 90%)',
            200: 'hsl(33, 98%, 80%)',
            300: 'hsl(33, 96%, 68%)',
            400: 'hsl(33, 95%, 58%)',
            500: 'hsl(33, 93%, 50%)',
            600: 'hsl(28, 92%, 43%)',
            700: 'hsl(24, 88%, 35%)',
            800: 'hsl(21, 82%, 27%)',
            900: 'hsl(18, 76%, 20%)',
          },
          sage: {
            50: 'hsl(147, 40%, 96%)',
            100: 'hsl(147, 38%, 88%)',
            200: 'hsl(147, 35%, 74%)',
            300: 'hsl(147, 32%, 60%)',
            400: 'hsl(147, 30%, 48%)',
            500: 'hsl(147, 32%, 38%)',
            600: 'hsl(147, 34%, 31%)',
            700: 'hsl(147, 36%, 24%)',
            800: 'hsl(147, 38%, 17%)',
            900: 'hsl(147, 40%, 11%)',
          },
          coral: {
            50: 'hsl(12, 100%, 96%)',
            100: 'hsl(12, 98%, 90%)',
            200: 'hsl(12, 95%, 80%)',
            300: 'hsl(12, 90%, 68%)',
            400: 'hsl(12, 85%, 57%)',
            500: 'hsl(12, 82%, 48%)',
            600: 'hsl(8, 80%, 40%)',
            700: 'hsl(5, 76%, 32%)',
          },
          sky: {
            50: 'hsl(198, 100%, 95%)',
            100: 'hsl(198, 95%, 88%)',
            200: 'hsl(198, 88%, 76%)',
            300: 'hsl(198, 80%, 62%)',
            400: 'hsl(198, 72%, 50%)',
            500: 'hsl(198, 72%, 40%)',
            600: 'hsl(198, 74%, 33%)',
          },
          plum: {
            50: 'hsl(270, 60%, 96%)',
            100: 'hsl(270, 55%, 90%)',
            200: 'hsl(270, 50%, 80%)',
            300: 'hsl(270, 48%, 67%)',
            400: 'hsl(270, 46%, 55%)',
            500: 'hsl(270, 44%, 44%)',
            600: 'hsl(270, 42%, 36%)',
          },
        },
        secondary: {
          DEFAULT: 'var(--color-secondary)',
          hover: 'var(--color-secondary-hover)',
          light: 'var(--color-secondary-light)',
          muted: 'var(--color-secondary-muted)',
        },
        success: {
          DEFAULT: 'var(--color-success)',
          bg: 'var(--color-success-bg)',
        },
        warning: {
          DEFAULT: 'var(--color-warning)',
          bg: 'var(--color-warning-bg)',
        },
        error: {
          DEFAULT: 'var(--color-error)',
          bg: 'var(--color-error-bg)',
        },
        info: {
          DEFAULT: 'var(--color-info)',
          bg: 'var(--color-info-bg)',
        },
        card: {
          bg: 'var(--card-bg)',
          border: 'var(--card-border)',
        },
        nav: {
          bg: 'var(--nav-bg)',
          border: 'var(--nav-border)',
          active: 'var(--nav-active)',
          inactive: 'var(--nav-inactive)',
        }
      },
      spacing: {
        '0': '0px',
        '1': '4px',
        '1.5': '6px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '7': '28px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
        '14': '56px',
        '16': '64px',
        '20': '80px',
        '24': '96px',
        '32': '128px',
      },
      borderRadius: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '20px',
        '2xl': '24px',
        '3xl': '28px',
        'pill': '999px',
        'full': '50%',
        'card': 'var(--card-radius)',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'sans-serif'],
        mono: ['"JetBrains Mono"', '"Fira Code"', '"Courier New"', 'monospace'],
      },
      fontSize: {
        'xs': '0.75rem',
        'sm': '0.8125rem',
        'base': '0.9375rem',
        'md': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '3.75rem',
      },
      fontWeight: {
        light: '300',
        regular: '400',
        medium: '500',
        semibold: '600',
        bold: '700',
        extrabold: '800',
      },
      lineHeight: {
        tight: '1.2',
        snug: '1.35',
        normal: '1.5',
        relaxed: '1.65',
        loose: '1.8',
      },
      letterSpacing: {
        tighter: '-0.04em',
        tight: '-0.02em',
        normal: '0em',
        wide: '0.02em',
        wider: '0.06em',
        widest: '0.12em',
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
        '2xl': 'var(--shadow-2xl)',
        'inner': 'inset 0 2px 4px 0 rgba(0,0,0,0.06)',
        'card': 'var(--card-shadow)',
        'card-hover': 'var(--card-shadow-hover)',
      },
      transitionDuration: {
        instant: '50ms',
        fast: '100ms',
        normal: '200ms',
        moderate: '300ms',
        slow: '400ms',
        deliberate: '600ms',
        cinematic: '800ms',
      },
      transitionTimingFunction: {
        sharp: 'cubic-bezier(0.4, 0, 0.6, 1)',
        standard: 'cubic-bezier(0.2, 0, 0, 1)',
        decelerate: 'cubic-bezier(0, 0, 0, 1)',
        accelerate: 'cubic-bezier(0.3, 0, 1, 1)',
        spring: 'cubic-bezier(0.35, 0, 0, 1.3)',
        bounce: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
      zIndex: {
        'below': '-1',
        'base': '0',
        'raised': '10',
        'overlay': '100',
        'dropdown': '200',
        'sticky': '300',
        'modal': '400',
        'toast': '500',
        'tooltip': '600',
      }
    },
  },
  plugins: [],
}
